server {
    listen 80;
    index index.php index.html;
    error_log  /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;
    
    # POINT D'ENTRÉE IMPORTANT : pointer vers le dossier public
    root /var/www/public;

    # Configuration pour les fichiers statiques (images, CSS, JS, SVG)
    location / {
        try_files \(uri\)uri/ /index.php?$query_string;
        gzip_static on;
    }

    # Empêcher Laravel de traiter les fichiers statiques manquants si nécessaire
    location ~* \.(jpg|jpeg|gif|png|css|js|ico|webp|svg|eot|ttf|woff|woff2)$ {
        expires max;
        log_not_found off;
        try_files $uri =404;
    }

    # Traitement des fichiers PHP via PHP-FPM
    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME \(document_root\)fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}
